config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources 'authors'
  end

  get 'about', to: 'about#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates_presence_of :first_name, :last_name

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "Author #{@author.name} was successfully created."
      redirect_to admin_authors_path
    else
      render 'new'
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      flash[:success] = 'Author was successfully updated.'
      redirect_to admin_author_path(@author)
    else
      render 'edit'
    end
  end

  def show
    @author = Author.find(params[:id])
    @page_title = @author.name
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:success] = "Successfully deleted author #{@author.name}"
    redirect_to admin_authors_path
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/authors_helper.rb
module Admin::AuthorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/views/about/index.html.erb
<% title 'About Emporium' %>
<p>Online bookstore located in downtown Manhattan, New York</p>
<h2>Mailing Address</h2>
<address>
  Emporium<br/>
  P.O. Box 0000<br/>
  Grand Cayman, Cayman Islands<br/>
</address>

app/views/admin/authors/_author.html.erb
<tr>
  <td><%= link_to author.name, admin_author_url(author) %></td>
  <td><%= link_to 'Edit', edit_admin_author_path(author) %></td>
  <td><%= button_to 'Delete',
                    admin_author_path(author),
                    method: :delete,
                    data: {
                      confirm: "Are you sure you want to delete author #{author.name}?"
                    },
                    class: 'btn btn-xs btn-danger' %>
  </td>
</tr>

app/views/admin/authors/_form.html.erb
<div class="row">
  <div class="form-group col-md-6">
    <%= label_tag 'first_name' %>
    <%= text_field 'author', 'first_name', class: 'form-control' %>
  </div>
</div>

<div class="row">
  <div class="form-group col-md-6">
    <%= label_tag 'last_name' %>
    <%= text_field 'author', 'last_name', class: 'form-control' %>
  </div>
</div>

app/views/admin/authors/create.html.erb
<h1>Admin::Authors#create</h1>
<p>Find me in app/views/admin/authors/create.html.erb</p>

app/views/admin/authors/edit.html.erb
<% title 'Edit author' %>
<h1><%= yield :title %></h1>
<%= form_tag admin_author_path(@author), method: :put do %>
  <%= render 'form' %>
  <%= submit_tag 'Edit', class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Show', admin_author_path(@author) %>
<%= link_to 'Back', admin_authors_path %>

app/views/admin/authors/index.html.erb
<% title 'Listing authors' %>
<h1><%= yield :title %></h1>
<table class="table table-stripe">
  <thead>
  <tr>
    <th>Name</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>
  <%= render partial: 'author', collection: @authors %>
  </tbody>
</table>

<p>
  <%= link_to 'Add a new author', new_admin_author_path %>
</p>

app/views/admin/authors/new.html.erb
<% title 'Create new author' %>
<h1><%= yield :title %></h1>

<%= form_tag admin_authors_path do %>
  <%= render 'form' %>
  <%= submit_tag 'Create', class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back', admin_authors_path %>

app/views/admin/authors/show.html.erb
<% title @page_title %>
<dl>
  <dt>First Name</dt>
  <dd><%= @author.first_name %></dd>
  <dt>Last Name</dt>
  <dd><%= @author.last_name %></dd>
</dl>

<p>
  <%= link_to 'Edit', edit_admin_author_path(@author) %> |
  <%= link_to 'Back', admin_authors_path %>
</p>

app/views/admin/authors/update.html.erb
<h1>Admin::Authors#update</h1>
<p>Find me in app/views/admin/authors/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : 'Emporium' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag 'application' %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Emporium</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Link1', '/path1' %></li>
            <li><%= link_to 'Link2', '/path2' %></li>
            <li><%= link_to 'Link3', '/path3' %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>